<?php

namespace Puli;

use Puli\Discovery\Api\ResourceDiscovery;
use Puli\Discovery\KeyValueStoreDiscovery;
use Puli\Factory\PuliFactory;
use Puli\Repository\Api\ResourceRepository;
use Puli\Repository\FilesystemRepository;
use Webmozart\KeyValueStore\JsonFileStore;

/**
 * Creates Puli's core services.
 *
 * This class was auto-generated by Puli.
 *
 * IMPORTANT: Before modifying the code below, set the "factory.auto-generate"
 * configuration key to false:
 *
 *     $ puli config factory.auto-generate false
 *
 * Otherwise any modifications will be overwritten!
 */
class GeneratedPuliFactory implements PuliFactory
{
    /**
     * Creates the resource repository.
     *
     * @return ResourceRepository The created resource repository.
     */
    public function createRepository()
    {
        if (!file_exists(__DIR__.'/repository')) {
            mkdir(__DIR__.'/repository', 0777, true);
        }
        
        $repo = new FilesystemRepository(__DIR__.'/repository', true);

        return $repo;
    }

    /**
     * Creates the resource discovery.
     *
     * @param ResourceRepository $repo The resource repository to read from.
     *
     * @return ResourceDiscovery The created resource discovery.
     */
    public function createDiscovery(ResourceRepository $repo)
    {
        $store = new JsonFileStore(__DIR__.'/bindings.json', true);

        $discovery = new KeyValueStoreDiscovery(
            $repo,
            $store
        );

        return $discovery;
    }
}
